# Generated by Django 3.0.8 on 2020-08-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_protfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sk_about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone_Number', models.IntegerField()),
                ('Email_Number', models.EmailField(max_length=254)),
                ('Fb_Urls', models.URLField()),
                ('Link_Urls', models.URLField()),
            ],
        ),
    ]
