# Generated by Django 3.0.8 on 2020-08-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_protfolio', '0002_sk_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sk_cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sk_cv', models.FileField(upload_to='all_image/')),
                ('cv_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
