# Generated by Django 3.0.8 on 2020-08-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_protfolio', '0003_sk_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sk_certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_Name', models.CharField(max_length=50)),
                ('Roll_Number', models.IntegerField()),
                ('Bord_Name', models.CharField(max_length=50)),
                ('Result', models.FloatField()),
                ('Certificate_Image', models.ImageField(upload_to='all_image/')),
            ],
        ),
    ]
