# Generated by Django 3.0.8 on 2020-08-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_protfolio', '0004_sk_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sk_online_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=50)),
                ('Institute_Name', models.CharField(max_length=50)),
                ('Result', models.CharField(max_length=40, null='')),
                ('Course_Image', models.ImageField(upload_to='all_image/')),
            ],
        ),
    ]
