# Generated by Django 3.0.8 on 2020-08-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_protfolio', '0005_sk_online_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest_Cata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interest_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sk_Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Date', models.DateTimeField(verbose_name='date published')),
                ('Img1_url', models.URLField()),
                ('Img_url', models.URLField()),
                ('vid_url', models.URLField()),
                ('Interset_catagary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_protfolio.Interest_Cata')),
            ],
        ),
    ]
