# Generated by Django 3.0.8 on 2020-08-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_protfolio', '0006_interest_cata_sk_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sk_interest',
            name='Img1_url',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='sk_interest',
            name='Img_url',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='sk_interest',
            name='vid_url',
            field=models.CharField(max_length=10000),
        ),
    ]
