# Generated by Django 3.0.8 on 2020-09-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_protfolio', '0007_auto_20200811_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Cata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_catagory_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='sk_interest',
            name='Img1_url',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='sk_interest',
            name='Img_url',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='sk_interest',
            name='vid_url',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=100)),
                ('Img1_url', models.CharField(blank=True, max_length=10000)),
                ('vid_url', models.CharField(blank=True, max_length=10000)),
                ('File1', models.FileField(blank=True, upload_to='all_image/')),
                ('File2', models.FileField(blank=True, upload_to='all_image/')),
                ('File3', models.FileField(blank=True, upload_to='all_image/')),
                ('Description', models.TextField(blank=True, max_length=10000)),
                ('Project_catagary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_protfolio.Project_Cata')),
            ],
        ),
    ]
