# Generated by Django 3.0.8 on 2020-09-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_protfolio', '0008_auto_20200913_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='File1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='File2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='File3',
        ),
        migrations.AddField(
            model_name='project',
            name='File_url',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
