# Generated by Django 3.0.8 on 2020-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_protfolio', '0009_auto_20200923_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Description',
        ),
        migrations.AddField(
            model_name='project',
            name='web_url',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
