# Generated by Django 3.0.8 on 2020-09-24 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_protfolio', '0010_auto_20200924_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
